### ISSUE TITLE
How  to get the data for this code.

### ISSUE THREAD

**Issue by ymmmmmy** [shubhadityaburela/DL-ROM#1]
Hello, could you tell me where i can get the data of this source code?

**Comment by shubhadityaburela** [comment]
I wrote this code for a very specialised purpose to suit the problems which I am working on. But I will add an executable python file in the repo sometime around next week with a synthetically created data set with plots of how the data looks like. That I think will give a pretty good idea about how to use the code.

**Comment by ymmmmmy** [comment]
That’s sounds excellent. Thank you very much!

**Comment by shubhadityaburela** [comment]
Closing this issue, as this is covered in another opened issue
